packages:
  - 'packages/**'

catalog:
  '@lit-protocol/lit-node-client-nodejs': 7.0.2
  '@lit-protocol/constants': 7.0.2
  '@lit-protocol/types': 7.0.2
  '@lit-protocol/contracts-sdk': 7.0.2
  '@lit-protocol/auth-helpers': 7.0.2
  'ethers': 5.7.2
